# Generated by Django 2.1.5 on 2019-02-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
