# Generated by Django 2.1.5 on 2019-02-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20190204_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='newsfeed',
            name='slug',
        ),
    ]
