# Generated by Django 2.1.5 on 2019-02-06 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_comment_page_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_page',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 6, 13, 19, 40, 897424)),
        ),
        migrations.AlterField(
            model_name='comment_page',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
