# Generated by Django 2.1.5 on 2019-02-06 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20190206_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='password_reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=400)),
                ('password', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='comment_page',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 6, 17, 49, 45, 900259)),
        ),
    ]
