# Generated by Django 2.1.5 on 2019-02-07 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20190206_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=400)),
                ('reason', models.TextField(default='', help_text='Please give a few sentences detailing why you would be a good writer for the site, and links to samples', max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='comment_page',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 7, 12, 23, 58, 585766)),
        ),
    ]
